### ISSUE TITLE
Statuses.create doesn't URL-encode properly

### ISSUE THREAD

**Issue by exsortis** [ornithocoder/MastodonKit#11]
If I create a new status using Statuses.create(status: "something with a ; in it", ...), the semi-colon does not get encoded properly during the POST, and ends up truncating the status text.

**Comment by ornithocoder** [comment]
Thanks @exsortis! I work on it tonight :-)

**Comment by ornithocoder** [comment]
@exsortis does this fixes it for you?

```swift
 func toString(parameter: Parameter) -> String? {
-    return parameter.value.flatMap { value in "\(parameter.name)=\(value)" }
+    return parameter.value?.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed).flatMap { value in
+        "\(parameter.name)=\(value)"
+    }
 }
```

**Comment by exsortis** [comment]
I think it should probably be .urlQueryAllowed instead of .urlHostAllowed, since it's a query parameter.

**Comment by ornithocoder** [comment]
Neither worked. I had to create a character set to make it work. Check it here https://mastodon.technology/@ornithocoder/682510

I'll cleanup my spike and update the tests.

**Comment by ornithocoder** [comment]
@exsortis this should fix it. These are unserved characters according to the [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.3). I tested after the change and was able to register an application, login, and post. Let me know what do you think. If this is OK for you I'll merge into master.

**Comment by exsortis** [comment]
LGTM

**Comment by exsortis** [comment]
BTW, your avatar is boss. +1

**Comment by ornithocoder** [comment]
@exsortis thanks! Your avatar is equally awesome ;-)

This is the iOS Developer I rendered when I was trying to learn Blender. I should render it again, I learned a few Blender tricks since this one.

![ios developer 7](https://cloud.githubusercontent.com/assets/19753339/25724081/d59f65e6-311a-11e7-9255-eca09f88919d.png)

PS: He's wearing the WWDC 2014 T-Shirt (the year Apple introduced Swift).

**Comment by exsortis** [comment]
That's awesome.
