### ISSUE TITLE
Add new parameters

### ISSUE THREAD

**Issue by ornithocoder** [ornithocoder/MastodonKit#7]
https://github.com/tootsuite/documentation/pull/105/files

https://github.com/tootsuite/documentation/pull/89/files

**Comment by vhbit** [comment]
Is it closed because it's already implemented but not yet pushed?

**Comment by ornithocoder** [comment]
@vhbit It's no master already (tag 1.0.4). It's implemented as a [optional parameter called range](https://github.com/ornithocoder/MastodonKit#range-and-limit).

**Comment by vhbit** [comment]
ahh, I've missed that. Thanks!

**Comment by ornithocoder** [comment]
No problem @vhbit! You're welcome :-) I decided to bundle those in a single optional model to avoid method with long signatures. And it's easier to handle with maps and flatMaps.
